name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build
        run: go build ./...
        working-directory: lib
      - name: Tests
        run: go test -v ./...
        working-directory: lib
      - name: Benchmarks
        run: go test -run=^$ -bench=. ./...
        working-directory: lib